import { access, readFile } from "node:fs/promises";
import path from "node:path";
import type { AgentFlowConfig } from "../config/defaults.js";
import type { ComposedPacks } from "../packs/manifest.js";
import type { RenderedFile } from "../renderer/conflict-policy.js";

export interface McpServerDefinition {
  command: string;
  args: string[];
  env: Record<string, string>;
  requiredEnv: string[];
}

export interface ResolvedMcpServer extends McpServerDefinition {
  name: string;
  enabled: boolean;
  required: boolean;
  known: boolean;
}

export interface McpHealthResult {
  renderedFiles: string[];
  warnings: string[];
  errors: string[];
}

const MCP_CATALOG: Record<string, McpServerDefinition> = {
  codeReviewGraph: {
    command: "npx",
    args: ["-y", "code-review-graph", "serve", "--root", "."],
    env: {},
    requiredEnv: []
  },
  playwright: {
    command: "npx",
    args: ["-y", "@playwright/mcp@latest"],
    env: {},
    requiredEnv: []
  },
  context7: {
    command: "npx",
    args: ["-y", "@upstash/context7-mcp@latest"],
    env: {},
    requiredEnv: []
  }
};

const MCP_TARGET_FILES = [
  ".mcp.json",
  path.join(".claude", "settings.json"),
  path.join(".codex", "mcp.codex.json")
];

export function resolveMcpServers(config: AgentFlowConfig, packs: ComposedPacks): ResolvedMcpServer[] {
  if (config.mcp.mode === "off") {
    return [];
  }

  const merged: AgentFlowConfig["mcp"]["servers"] = {};

  for (const [name, server] of Object.entries(packs.mcpServers)) {
    merged[name] = { ...server };
  }

  for (const [name, server] of Object.entries(config.mcp.servers)) {
    merged[name] = { ...server };
  }

  return Object.entries(merged)
    .filter(([, server]) => server.enabled)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, server]) => {
      const definition = MCP_CATALOG[name];
      return {
        name,
        enabled: server.enabled,
        required: server.required || config.mcp.mode === "strict",
        known: definition !== undefined,
        ...(definition ?? {
          command: "",
          args: [],
          env: {},
          requiredEnv: []
        })
      };
    });
}

export function renderMcpFiles(config: AgentFlowConfig, packs: ComposedPacks): RenderedFile[] {
  const servers = resolveMcpServers(config, packs).filter((server) => server.known);

  if (servers.length === 0) {
    return [];
  }

  const mcpServers = Object.fromEntries(servers.map((server) => [
    server.name,
    {
      command: server.command,
      args: server.args,
      env: server.env
    }
  ]));
  const shared = stringifyJson({ mcpServers });
  const codex = stringifyJson({
    mcpServers,
    notes: "Generated by Agent Flow. Server commands are portable and must not contain machine-local absolute paths."
  });

  return [
    { path: ".mcp.json", content: shared },
    {
      path: path.join(".claude", "settings.json"),
      content: stringifyJson({ mcpServers })
    },
    {
      path: path.join(".codex", "mcp.codex.json"),
      content: codex
    }
  ];
}

export async function checkMcpHealth(root: string, config: AgentFlowConfig, packs: ComposedPacks): Promise<McpHealthResult> {
  const servers = resolveMcpServers(config, packs);
  const warnings: string[] = [];
  const errors: string[] = [];

  if (config.mcp.mode === "off" || servers.length === 0) {
    return { renderedFiles: [], warnings, errors };
  }

  for (const filePath of MCP_TARGET_FILES) {
    const content = await readOptional(path.join(root, filePath));

    if (content === null) {
      warnings.push(`MCP config file is missing: ${toPortablePath(filePath)}. Run agent-flow sync.`);
      continue;
    }

    if (containsUnsafeAbsolutePath(content)) {
      errors.push(`MCP config file contains a machine-local absolute path: ${toPortablePath(filePath)}.`);
    }
  }

  for (const server of servers) {
    if (!server.known) {
      const message = `MCP server '${server.name}' has no portable Agent Flow renderer.`;
      (server.required ? errors : warnings).push(message);
      continue;
    }

    if (!(await commandExists(server.command))) {
      const message = `MCP server '${server.name}' command is missing from PATH: ${server.command}.`;
      (server.required ? errors : warnings).push(message);
    }

    for (const envName of server.requiredEnv) {
      if (!process.env[envName]) {
        const message = `MCP server '${server.name}' requires environment variable ${envName}.`;
        (server.required ? errors : warnings).push(message);
      }
    }
  }

  return {
    renderedFiles: MCP_TARGET_FILES.map(toPortablePath),
    warnings,
    errors
  };
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function containsUnsafeAbsolutePath(content: string): boolean {
  return /(?:^|["'\s])(?:\/Users\/|\/home\/|\/private\/|[A-Za-z]:\\)/.test(content);
}

async function commandExists(command: string): Promise<boolean> {
  const pathValue = process.env.PATH ?? "";
  const extensions = process.platform === "win32" ? ["", ".exe", ".cmd", ".bat"] : [""];

  for (const directory of pathValue.split(path.delimiter)) {
    if (!directory) {
      continue;
    }

    for (const extension of extensions) {
      try {
        await access(path.join(directory, `${command}${extension}`));
        return true;
      } catch {
        // Try the next PATH candidate.
      }
    }
  }

  return false;
}

async function readOptional(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, "utf8");
  } catch {
    return null;
  }
}

function toPortablePath(filePath: string): string {
  return filePath.split(path.sep).join("/");
}
